resourceServers:
  - name: api-test
    identifier: https://example.com/api/v1/
    allow_offline_access: true
    enforce_policies: true
    scopes:
      - value: read:test
        description: Receive test responses
    signing_alg: RS256
    skip_consent_for_verifiable_first_party_clients: false
    token_dialect: access_token
    token_lifetime: 7200
    token_lifetime_for_web: 7200
clients:
  - name: mfa-settings
    allowed_clients: []
    allowed_logout_urls:
      - https://localhost:3000
      - http://localhost:3000
    app_type: regular_web
    callbacks:
      - https://localhost:3000/mfa/callback
      - http://localhost:3000/mfa/callback
    client_aliases: []
    cross_origin_auth: false
    custom_login_page_on: true
    grant_types:
      - authorization_code
      - refresh_token
      - client_credentials
      - http://auth0.com/oauth/grant-type/mfa-oob
      - http://auth0.com/oauth/grant-type/mfa-otp
      - http://auth0.com/oauth/grant-type/mfa-recovery-code
    is_first_party: true
    is_token_endpoint_ip_header_trusted: false
    jwt_configuration:
      alg: RS256
      lifetime_in_seconds: 36000
      secret_encoded: false
    native_social_login:
      apple:
        enabled: false
      facebook:
        enabled: false
    oidc_conformant: true
    refresh_token:
      expiration_type: non-expiring
      leeway: 0
      infinite_token_lifetime: true
      infinite_idle_token_lifetime: true
      token_lifetime: 31557600
      idle_token_lifetime: 2592000
      rotation_type: non-rotating
    sso_disabled: false
    token_endpoint_auth_method: client_secret_post
  - name: rwa-test
    addons: {}
    allowed_clients: []
    allowed_logout_urls:
      - http://localhost:3000/rwa
      - https://localhost:3000/rwa
    allowed_origins: []
    app_type: regular_web
    callbacks:
      - http://localhost:3000/rwa/callback
      - https://localhost:3000/rwa/callback
    client_aliases: []
    cross_origin_auth: false
    cross_origin_authentication: true
    custom_login_page_on: true
    grant_types:
      - authorization_code
      - refresh_token
      - client_credentials
    is_first_party: true
    is_token_endpoint_ip_header_trusted: true
    jwt_configuration:
      alg: RS256
      lifetime_in_seconds: 36000
      secret_encoded: false
    logo_uri: ''
    native_social_login:
      apple:
        enabled: false
      facebook:
        enabled: false
    oidc_conformant: true
    organization_require_behavior: no_prompt
    organization_usage: deny
    refresh_token:
      expiration_type: non-expiring
      leeway: 0
      infinite_token_lifetime: true
      infinite_idle_token_lifetime: true
      token_lifetime: 31557600
      idle_token_lifetime: 2592000
      rotation_type: non-rotating
    sso_disabled: false
    token_endpoint_auth_method: client_secret_post
    web_origins: []
  - name: spa-test
    allowed_clients: []
    allowed_logout_urls:
      - http://localhost:3000/spa/auth0spajs
      - http://localhost:3000/spa/auth0js
      - http://localhost:3000/spa/lock
      - https://localhost:3000/spa/auth0spajs
      - https://localhost:3000/spa/auth0js
      - https://localhost:3000/spa/lock
    allowed_origins:
      - http://localhost:3000/
      - https://localhost:3000/
    app_type: spa
    callbacks:
      - http://localhost:3000/spa/auth0spajs
      - http://localhost:3000/spa/auth0js
      - http://localhost:3000/spa/lock
      - https://localhost:3000/spa/auth0spajs
      - https://localhost:3000/spa/auth0js
      - https://localhost:3000/spa/lock
    client_aliases: []
    cross_origin_auth: false
    cross_origin_authentication: true
    custom_login_page_on: true
    grant_types:
      - authorization_code
      - refresh_token
    is_first_party: true
    is_token_endpoint_ip_header_trusted: false
    jwt_configuration:
      alg: RS256
      lifetime_in_seconds: 36000
      secret_encoded: false
    native_social_login:
      apple:
        enabled: false
      facebook:
        enabled: false
    oidc_conformant: true
    organization_require_behavior: no_prompt
    refresh_token:
      expiration_type: expiring
      leeway: 0
      token_lifetime: 1200
      idle_token_lifetime: 1000
      infinite_token_lifetime: false
      infinite_idle_token_lifetime: false
      rotation_type: rotating
    sso_disabled: false
    token_endpoint_auth_method: none
    web_origins:
      - http://localhost:3000
      - https://localhost:3000
databases:
  - name: Username-Password-Authentication
    strategy: auth0
    enabled_clients:
      - mfa-settings
      - rwa-test
      - spa-test
    is_domain_connection: false
    options:
      mfa:
        active: true
        return_enroll_settings: true
      validation:
        username:
          max: 15
          min: 1
      disable_signup: false
      passwordPolicy: good
      passkey_options:
        challenge_ui: both
        local_enrollment_enabled: true
        progressive_enrollment_enabled: true
      strategy_version: 2
      requires_username: false
      authentication_methods:
        passkey:
          enabled: false
        password:
          enabled: true
      brute_force_protection: true
    realms:
      - Username-Password-Authentication
